In [1]:
import numpy as np

In [6]:
influencer = np.array([1200, 1500, 6700.37866, 1250000], dtype="int64")
print(influencer)
print(influencer.shape)
print(influencer.ndim)
print(influencer.dtype)

zomato = np.arange(101, 111) # Changed to generate 10 consecutive orders
print(zomato)
print(zomato.size)

spotify = np.eye(3)
print(spotify)
# The diagonal values represent a 'like' from an artist to their own song or a self-endorsement within the playlist.

cricket_score = np.array([45, 67, 120, 89, 54], dtype="int64")
print(cricket_score.itemsize)


[   1200    1500    6700 1250000]
(4,)
1
int64
[101 102 103 104 105 106 107 108 109 110]
10
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
8
